/**
 * MCP Server Command
 *
 * Comprehensive MCP (Model Context Protocol) server exposing ALL prlt commands
 * as tools for AI agent integration.
 *
 * Tools are auto-generated from oclif command definitions:
 * - Flags/args → Zod schemas
 * - Handlers → ctx.runCommand() passthrough (routes through provider adapter)
 * - Manual overrides in mcp/tools/overrides/ take precedence
 *
 * Usage in Claude Code config:
 * ```json
 * {
 *   "mcpServers": {
 *     "prlt": { "command": "prlt", "args": ["mcp-server"] }
 *   }
 * }
 * ```
 */

import { Command } from '@oclif/core'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { execSync } from 'node:child_process'
import * as path from 'node:path'
import { openWorkspaceDatabase } from '../lib/database/index.js'
import { getPMOContext } from '../lib/pmo/pmo-context.js'
import type { McpToolContext } from '../lib/mcp/types.js'
import { getWorkspaceInfo } from '../lib/agents/commands.js'
import { ExecutionStorage } from '../lib/execution/storage.js'
import { registerAutoGeneratedTools } from '../lib/mcp/generator.js'
import type { OclifCommand } from '../lib/mcp/generator.js'
import { getOverriddenToolNames, registerOverrides } from '../lib/mcp/tools/overrides/index.js'

export default class McpServerCommand extends Command {
  static description = 'Start MCP server for AI agent integration (exposes all prlt commands as tools)'

  static hidden = true

  static examples = ['<%= config.bin %> mcp-server']

  async run(): Promise<void> {
    // Initialize PMO context (may be null if not in a workspace)
    let pmoContext = null
    try {
      pmoContext = await getPMOContext({ logger: () => {} })
    } catch {
      pmoContext = null
    }

    // Create MCP server
    const server = new McpServer({
      name: 'prlt',
      version: this.config.version,
    })

    // Try to initialize workspace context for execution support
    let workspaceContext: ReturnType<NonNullable<McpToolContext['getWorkspaceContext']>> | null = null
    try {
      const workspaceInfo = getWorkspaceInfo()
      if (workspaceInfo && pmoContext) {
        const db = openWorkspaceDatabase(workspaceInfo.path)
        const executionStorage = new ExecutionStorage(db)
        workspaceContext = {
          workspaceInfo,
          executionStorage,
          db,
          pmoPath: pmoContext.pmoPath,
        }
      }
    } catch {
      // Not in a workspace — workspace context will be null
    }

    // Create tool context
    const ctx: McpToolContext = {
      get storage() {
        if (!pmoContext) {
          throw new Error('PMO not initialized. Run "prlt new" first.')
        }
        return pmoContext.storage
      },
      runCommand: (cmd: string): string => {
        try {
          const result = execSync(cmd, {
            encoding: 'utf-8',
            cwd: process.cwd(),
            env: {
              ...process.env,
              PATH: `${path.dirname(process.execPath)}:${process.env.PATH}`,
            },
            maxBuffer: 10 * 1024 * 1024,
          })
          return result.trim()
        } catch (error: unknown) {
          const execError = error as { stderr?: string; stdout?: string; message?: string }
          if (execError.stderr) return execError.stderr.trim()
          if (execError.stdout) return execError.stdout.trim()
          throw error
        }
      },
      getWorkspaceContext: workspaceContext
        ? () => workspaceContext!
        : undefined,
    }

    // Register manual overrides first (they take precedence)
    registerOverrides(server, ctx)
    const overriddenNames = getOverriddenToolNames()

    // Auto-generate tools from oclif command definitions
    // Each tool invokes the CLI via ctx.runCommand(), routing through
    // the provider adapter instead of accessing storage directly.
    registerAutoGeneratedTools(
      server,
      ctx,
      this.config.commands as unknown as OclifCommand[],
      overriddenNames,
    )

    // Connect via stdio transport
    const transport = new StdioServerTransport()
    await server.connect(transport)
  }
}
