/**
 * MCP tool drift detection test (PRLT-1112)
 *
 * Verifies that every CLI command has a corresponding MCP tool — either
 * auto-generated or manually overridden. Fails if a CLI command exists
 * without a matching MCP tool (unless it is explicitly excluded).
 *
 * This prevents drift between the CLI and MCP server: when someone adds
 * a new command, this test reminds them to ensure MCP coverage.
 */

import { expect } from 'chai'
import * as fs from 'node:fs'
import * as path from 'node:path'
import {
  EXCLUDED_COMMANDS,
  EXCLUDED_PLUGINS,
  commandIdToToolName,
} from '../../src/lib/mcp/generator.js'
import { getOverriddenToolNames } from '../../src/lib/mcp/tools/overrides/index.js'

/**
 * Recursively walk the commands directory and derive oclif command IDs
 * from the file paths. This mirrors how oclif discovers commands.
 *
 * commands/ticket/list.ts  → "ticket:list"
 * commands/agent/staff/add.ts → "agent:staff:add"
 * commands/ps.ts → "ps"
 * commands/ticket/index.ts → "ticket"
 */
function discoverCommandIds(commandsDir: string, prefix = ''): string[] {
  const ids: string[] = []

  if (!fs.existsSync(commandsDir)) return ids

  const entries = fs.readdirSync(commandsDir, { withFileTypes: true })

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const subIds = discoverCommandIds(
        path.join(commandsDir, entry.name),
        prefix ? `${prefix}:${entry.name}` : entry.name,
      )
      ids.push(...subIds)
    } else if (entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')) {
      const basename = entry.name.replace(/\.ts$/, '')

      if (basename === 'index') {
        // index.ts → topic command (e.g., commands/ticket/index.ts → "ticket")
        if (prefix) ids.push(prefix)
      } else {
        // regular command file
        const id = prefix ? `${prefix}:${basename}` : basename
        ids.push(id)
      }
    }
  }

  return ids
}

/**
 * Plugins that ship their own commands — these are NOT in our commands/ dir
 * so we don't need to account for them in the drift check.
 */
const PLUGIN_COMMAND_PREFIXES = ['help', 'commands', 'plugins']

describe('MCP Tool Drift Detection (PRLT-1112)', () => {
  const commandsDir = path.resolve(
    import.meta.dirname,
    '../../src/commands',
  )
  const commandIds = discoverCommandIds(commandsDir)
  const overriddenNames = getOverriddenToolNames()

  it('should discover CLI commands from the source directory', () => {
    // Sanity check — we should find a reasonable number of commands
    expect(commandIds.length).to.be.greaterThan(50)
  })

  it('should have an MCP tool for every CLI command (auto-generated or overridden)', () => {
    const uncovered: string[] = []

    for (const id of commandIds) {
      // Skip explicitly excluded commands
      if (EXCLUDED_COMMANDS.has(id)) continue

      // Skip plugin-like commands that are not from our codebase
      if (PLUGIN_COMMAND_PREFIXES.some(p => id === p || id.startsWith(`${p}:`))) continue

      const toolName = commandIdToToolName(id)

      // A command is covered if it would be auto-generated OR has a manual override
      // Since auto-generation covers everything not excluded, we just check
      // that the command is not excluded AND not in an excluded plugin.
      // The override check ensures manual tools are also counted.
      const isOverridden = overriddenNames.has(toolName)
      const isAutoGenerated = !EXCLUDED_COMMANDS.has(id)

      if (!isOverridden && !isAutoGenerated) {
        uncovered.push(id)
      }
    }

    expect(
      uncovered,
      `CLI commands without MCP tools: ${uncovered.join(', ')}\n` +
      'Add to EXCLUDED_COMMANDS in generator.ts or create an override in mcp/tools/overrides/',
    ).to.have.length(0)
  })

  it('should not have exclusions for commands that do not exist', () => {
    const staleExclusions: string[] = []

    for (const excluded of EXCLUDED_COMMANDS) {
      if (!commandIds.includes(excluded)) {
        staleExclusions.push(excluded)
      }
    }

    expect(
      staleExclusions,
      `Stale exclusions in EXCLUDED_COMMANDS (commands no longer exist): ${staleExclusions.join(', ')}`,
    ).to.have.length(0)
  })

  it('should not have overrides for tool names that conflict with auto-generated names', () => {
    // Verify that override tool names correspond to real commands
    const autoToolNames = new Set(
      commandIds
        .filter(id => !EXCLUDED_COMMANDS.has(id))
        .map(commandIdToToolName),
    )

    const orphanOverrides: string[] = []
    for (const name of overriddenNames) {
      if (!autoToolNames.has(name)) {
        orphanOverrides.push(name)
      }
    }

    // Orphan overrides are allowed (they could be custom MCP-only tools)
    // but we flag them as a warning for awareness
    if (orphanOverrides.length > 0) {
      console.warn(
        `[info] Override tool names without matching CLI commands: ${orphanOverrides.join(', ')}`,
      )
    }
  })

  it('should generate correct tool names from command IDs', () => {
    expect(commandIdToToolName('ticket:list')).to.equal('ticket_list')
    expect(commandIdToToolName('agent:staff:add')).to.equal('agent_staff_add')
    expect(commandIdToToolName('ps')).to.equal('ps')
    expect(commandIdToToolName('mcp-server')).to.equal('mcp_server')
  })
})
