#!/bin/bash

# PMO Board Initialization Script
# Creates a new PMO structure or updates existing one

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
BOARD_TYPE="${1:-flow}"
REPO_NAME="${2:-$(basename $(pwd))}"

# Validate board type
if [[ "$BOARD_TYPE" != "flow" && "$BOARD_TYPE" != "5-tool-founder" ]]; then
    echo -e "${YELLOW}Invalid board type: $BOARD_TYPE${NC}"
    echo "Usage: $0 [flow|5-tool-founder] [repo-name]"
    exit 1
fi

echo -e "${BLUE}🚀 Initializing PMO Board${NC}"
echo "Board Type: $BOARD_TYPE"
echo "Repository: $REPO_NAME"

# Create PMO directory structure
mkdir -p pmo/specs/{backlog,active,completed}
mkdir -p pmo/scripts

# Create config.yml
cat > pmo/config.yml << 'EOF'
# PMO Configuration
# Generated by pmo-init

# Type of PMO setup
# - single: PMO for single repository (default)
# - multi: PMO tracking multiple repositories  
# - rollup: Aggregated view of multiple PMOs
type: single

# Repository configuration
repository:
  name: REPO_NAME_PLACEHOLDER
  type: primary

# Future: Multi-repo tracking
# repos:
#   - name: project-a
#     path: ../project-a
#     kanban: pmo/kanban.md
#   - name: project-b  
#     path: ../project-b
#     kanban: pmo/kanban.md

# Sync settings
sync:
  # Location mode: internal (in repo) or external (separate repo)
  mode: internal
  # Auto-merge PMO updates to main
  auto_merge: true
  # Protected main branch
  protected_main: true

# Kanban settings
kanban:
  # Default columns for new boards
  columns:
    - "📥 Backlog"
    - "🎯 Ready"
    - "🚀 In Progress"
    - "🔄 PR Open"
    - "👀 In Review"
    - "✅ Done"
    - "🚫 Blocked"
  
  # Card template
  card_template: |
    - [ ] [[{{slug}}]]
      **Priority:** {{priority}} / **Urgency:** {{urgency}}
      **Points:** {{points}}
      **Category:** {{category}} / **Status:** {{status}}
      **Owner:** @{{owner}} / **Agent:** @{{agent}}
      **Timeline:** Started {{started}} • Due {{due}} • Completed {{completed}}
      **Spec:** [[specs/{{slug}}.md]]
      ***
      {{description}}
  
  # Priority options (Importance)
  priority_options:
    - HIGH    # Critical to success
    - MEDIUM  # Important but not critical  
    - LOW     # Nice to have
  
  # Urgency options (Time Sensitivity)
  urgency_options:
    - NOW     # Blocking/deadline this week
    - SOON    # Needed this month
    - LATER   # No time pressure
  
  # Point scale (Fibonacci)
  point_scale:
    1:  "Trivial (~2 hours) - Config change, README update"
    2:  "Simple (half day) - Small bug fix, add flag"
    3:  "Standard (1 day) - New endpoint, component"
    5:  "Complex (2-3 days) - Feature with tests"
    8:  "Large (1 week) - Multi-component feature"
    13: "Epic (1-2 weeks) - Consider splitting"
    21: "Too large - Must split into smaller tickets"

# Agent settings
agents:
  # Default agent workspaces
  workspaces:
    - 4runner
    - camry
    - fj40
    - hilux
  # Agent assignment mode: auto (round-robin) or manual
  assignment: manual

# Integration settings
integrations:
  # Obsidian compatibility
  obsidian:
    enabled: true
    kanban_plugin: board
  
  # GitHub integration
  github:
    # Auto-create PR descriptions from specs
    pr_from_spec: true
    # Add ticket links to commits
    link_commits: true
EOF

# Replace placeholder with actual repo name
sed -i.bak "s/REPO_NAME_PLACEHOLDER/$REPO_NAME/" pmo/config.yml && rm pmo/config.yml.bak

# Create kanban.md based on board type
if [[ "$BOARD_TYPE" == "5-tool-founder" ]]; then
    # 5-Tool Founder Board
    cat > pmo/kanban.md << 'EOF'
---
kanban-plugin: board
---

## 📥 Triage

- [ ] [[example-idea]]
  **Priority:** TBD / **Urgency:** TBD
  **Points:** TBD
  **Category:** TBD / **Status:** Triage
  **Owner:** unassigned / **Agent:** unassigned
  **Timeline:** Started - • Due - • Completed -
  **Spec:** [[specs/backlog/example-idea.md]]
  ***
  Raw idea - needs triage and categorization

## 🏗️ Build Queue

- [ ] [[example-feature]]
  **Priority:** MEDIUM / **Urgency:** SOON
  **Points:** 5
  **Category:** BUILD / **Status:** Ready
  **Owner:** unassigned / **Agent:** unassigned
  **Timeline:** Started - • Due - • Completed -
  **Spec:** [[specs/backlog/example-feature.md]]
  ***
  Example build task - replace with real work

## 📈 Grow Queue

## 🛟 Support Queue

## ⚙️ BizOps Queue

## 🎯 Strategy Queue

## 🚀 In Progress

## 🔄 PR/Review

## ✅ Merged

## 🚀 Released

%% kanban:settings
```
{"kanban-plugin":"board","list-collapse":[]}
```
%%
EOF
else
    # Standard Flow Board
    cat > pmo/kanban.md << 'EOF'
---
kanban-plugin: board
---

## 📥 Backlog

- [ ] [[example-feature]]
  **Priority:** MEDIUM / **Urgency:** SOON
  **Points:** 5
  **Category:** BUILD / **Status:** Backlog
  **Owner:** unassigned / **Agent:** unassigned
  **Timeline:** Started - • Due - • Completed -
  **Spec:** [[specs/backlog/example-feature.md]]
  ***
  Example feature card - replace with real work

## 🎯 Ready

## 🚀 In Progress

## 🔄 PR/Review

## ✅ Merged

## 🚀 Released

## 🚫 Blocked

%% kanban:settings
```
{"kanban-plugin":"board","list-collapse":[]}
```
%%
EOF
fi

# Create README for PMO
cat > pmo/README.md << 'EOF'
# PMO (Project Management Office)

This directory contains the project management structure for this repository.

## Structure

```
pmo/
├── config.yml          # PMO configuration
├── kanban.md          # Main kanban board (Obsidian-compatible)
├── specs/             # Detailed specifications for work items
│   ├── backlog/       # Unstarted specs
│   ├── active/        # In-progress specs
│   └── completed/     # Finished specs
└── scripts/           # PMO automation scripts
```

## Usage

### Viewing the Board
- Open `kanban.md` in Obsidian with the Kanban plugin
- Or view as markdown in any editor

### Claiming Work
```bash
pmo claim "implement-oauth"        # Claims ticket and creates feature branch
pmo status "Working on API calls"  # Updates ticket status
pmo complete "implement-oauth"     # Marks as complete
```

### Creating New Tickets
```bash
pmo create "fix-memory-leak" --priority HIGH --category BUILD
```

### Syncing PMO Updates
PMO updates are pushed directly to main branch (auto-merged if configured).
Feature work stays on feature branches.

## Workflow

1. **Pick work**: Agent/developer claims ticket from Ready column
2. **Update PMO**: Ticket moves to In Progress (commits to main)
3. **Create branch**: Feature branch created for implementation
4. **Do work**: Implementation on feature branch
5. **Open PR**: Ticket moves to PR Open
6. **Review**: Ticket in Review column during code review
7. **Merge**: Feature merges, ticket moves to Done

## Priority vs Urgency (Eisenhower Matrix)

Cards have both Priority (importance) and Urgency (time sensitivity):

- **HIGH/NOW**: 🔥 Do immediately (production issues, blockers)
- **HIGH/LATER**: 📅 Schedule (important refactors, strategic work)
- **LOW/NOW**: 🤔 Delegate or quick win (time-sensitive but not critical)
- **LOW/LATER**: 🗑️ Consider eliminating

Priority Options: HIGH, MEDIUM, LOW
Urgency Options: NOW (this week), SOON (this month), LATER (no pressure)

## Story Points (Fibonacci Scale)

We use Fibonacci numbers for effort estimation to capture uncertainty:

| Points | Effort | Examples |
|--------|--------|----------|
| **1** | ~2 hours | Update README, config change, fix typo |
| **2** | Half day | Small bug fix, add feature flag, update deps |
| **3** | 1 day | New API endpoint, React component, DB migration |
| **5** | 2-3 days | Feature with tests, OAuth integration, API redesign |
| **8** | 1 week | Multi-component feature, service refactor |
| **13** | 1-2 weeks | Epic - consider splitting into smaller tickets |
| **21** | Too large | Must split - no single ticket should be this big |

### Why Fibonacci?
- Forces relative sizing decisions
- Acknowledges that uncertainty grows with size
- Prevents false precision in estimates
- Enables velocity tracking over time

## Multi-Repo Support (Future)

This PMO is designed to support multi-repository tracking.
See `config.yml` for configuration options.
EOF

# Create comprehensive spec template for AI agents
cat > pmo/specs/backlog/example-feature.md << 'EOF'
# Feature Name

## 🎯 Goal
_One sentence describing what success looks like for the user_

Example: Users can login with Google OAuth in under 3 clicks and stay logged in across sessions.

## 📋 Context
_Background information the agent needs to understand the problem_

- **Current State**: How things work today (if applicable)
- **Problem**: What's broken or missing
- **User Impact**: Who this affects and how
- **Business Value**: Why this matters now

## ✅ Acceptance Criteria
_Specific, testable requirements that must be met_

- [ ] User can do X and see Y result
- [ ] System handles edge case Z gracefully  
- [ ] Performance: Operation completes in < Nms
- [ ] Security: Data is encrypted/validated/authorized
- [ ] Accessibility: Feature works with screen readers
- [ ] Mobile: Feature is responsive on mobile devices

## 🚫 Out of Scope
_Explicitly what NOT to do (prevents scope creep)_

- Not implementing user preferences UI (separate ticket)
- Not refactoring the entire auth system
- Not adding support for other OAuth providers yet

## 🔧 Technical Approach
_Guidance for implementation without dictating exact code_

### Preferred Patterns
- Use existing `AuthService` for token management
- Follow repository's error handling pattern (see `src/lib/errors.ts`)
- Implement using TypeScript with full type safety

### Architecture Notes
- Frontend: React component in `src/components/auth/`
- Backend: Express middleware in `src/middleware/auth/`
- Database: Add columns to `users` table for OAuth fields
- State Management: Use existing Redux auth slice

### Key Files to Modify
- `src/routes/auth.ts` - Add OAuth routes
- `src/components/LoginForm.tsx` - Add OAuth button
- `src/services/auth.service.ts` - Add OAuth methods
- `.env.example` - Document new environment variables

## 📝 Implementation Tasks
_Ordered checklist for the agent to follow_

- [ ] Research: Review existing auth implementation in codebase
- [ ] Setup: Add OAuth app in Google Cloud Console
- [ ] Backend: Implement OAuth callback endpoint
- [ ] Backend: Add token refresh logic
- [ ] Frontend: Create OAuth login button component
- [ ] Frontend: Handle OAuth redirect flow
- [ ] Database: Migration for OAuth fields
- [ ] Tests: Unit tests for auth service
- [ ] Tests: E2E test for full OAuth flow
- [ ] Docs: Update README with OAuth setup instructions
- [ ] Security: Audit for CSRF/XSS vulnerabilities
- [ ] Deploy: Add production OAuth credentials to secrets

## 🧪 Test Scenarios
_Specific cases to test_

### Happy Path
1. User clicks "Login with Google"
2. Redirected to Google, approves permissions
3. Redirected back, account created/linked
4. User sees dashboard with their name

### Edge Cases
- User denies Google permissions
- OAuth token expires during session
- User's Google email already linked to another account
- Network timeout during OAuth callback
- User has cookies disabled

## 📊 Validation
_How to verify the implementation works_

### Manual Testing
- [ ] Login works on Chrome, Firefox, Safari
- [ ] Login works on iOS and Android
- [ ] Refresh token renews automatically
- [ ] Logout clears all OAuth tokens

### Automated Checks
- [ ] All tests pass: `npm test`
- [ ] No type errors: `npm run typecheck`  
- [ ] No lint errors: `npm run lint`
- [ ] Security scan passes: `npm audit`

### Performance Metrics
- OAuth callback completes in < 2 seconds
- Token refresh happens without user noticing
- No memory leaks after 100 login/logout cycles

## 🔗 Dependencies & Blockers
_What needs to be in place first_

### Prerequisites
- [ ] Google Cloud project with OAuth 2.0 credentials
- [ ] SSL certificate for OAuth redirect URL
- [ ] Environment variables set in `.env`

### Related Tickets
- Depends on: [[setup-ssl-certificates]]
- Blocks: [[implement-github-oauth]]
- Related: [[add-user-preferences]]

## 💡 Examples & References
_Code examples or reference implementations_

### Similar Implementations
- [Passport.js Google OAuth example](https://github.com/passport/express-4.x-google-oauth2-example)
- Our existing email/password auth: `src/services/auth.service.ts:L45-L120`

### API Response Format
```json
{
  "user": {
    "id": "123",
    "email": "user@example.com",
    "provider": "google",
    "name": "John Doe"
  },
  "token": "jwt-token-here",
  "refreshToken": "refresh-token-here"
}
```

### Environment Variables Needed
```env
GOOGLE_CLIENT_ID=your-client-id
GOOGLE_CLIENT_SECRET=your-client-secret
GOOGLE_REDIRECT_URI=https://yourapp.com/auth/google/callback
JWT_SECRET=your-jwt-secret
```

## ⚠️ Risks & Mitigations
_Potential problems and how to handle them_

| Risk | Impact | Mitigation |
|------|--------|------------|
| Google API changes | Auth breaks | Version lock OAuth library, monitor deprecation notices |
| Token leakage | Account takeover | Use httpOnly cookies, implement CSRF protection |
| Rate limiting | Users can't login | Implement exponential backoff, cache tokens properly |

## 📈 Success Metrics
_How we'll know this worked_

- 50% of new users choose OAuth over email/password
- Login success rate > 95%
- Time to login reduced from 45s to 15s
- Support tickets about forgotten passwords reduced by 30%

## 🤖 AI Agent Notes
_Specific guidance for AI implementation_

### Do's
- ✅ Use existing patterns found in the codebase
- ✅ Ask for clarification if acceptance criteria conflicts
- ✅ Write comprehensive tests for auth flows
- ✅ Add detailed error messages for debugging

### Don'ts
- ❌ Don't store tokens in localStorage (use httpOnly cookies)
- ❌ Don't implement custom crypto (use established libraries)
- ❌ Don't skip error handling for "happy path only"
- ❌ Don't hardcode any credentials, even in tests

### When Stuck
If blocked, try these in order:
1. Search codebase for similar patterns
2. Check `docs/` folder for architecture decisions
3. Review recent PRs for team conventions
4. Ask for clarification rather than making assumptions

---
*Spec Version: 1.0 | Last Updated: YYYY-MM-DD | Author: @username*
EOF

# Create PMO abstraction script
cat > pmo/scripts/pmo.sh << 'EOF'
#!/bin/bash
# PMO abstraction layer - works regardless of PMO location

source "$(dirname "$0")/../config.yml" 2>/dev/null || source pmo/config.yml

# Detect PMO location
if [[ "$sync_mode" == "external" ]]; then
    PMO_PATH="../$(basename $(pwd))-pmo"
else
    PMO_PATH="./pmo"
fi

# Common PMO operations
case "$1" in
    claim)
        ticket="$2"
        # Update kanban to show claimed
        # Create feature branch
        ;;
    status)
        # Update ticket status
        ;;
    complete)
        # Mark ticket as complete
        ;;
    *)
        echo "Usage: pmo {claim|status|complete} [args]"
        ;;
esac
EOF

chmod +x pmo/scripts/pmo.sh

# Create .gitignore for PMO
cat > pmo/.gitignore << 'EOF'
# PMO temporary files
*.tmp
*.bak
.DS_Store

# Local PMO overrides
local-config.yml
EOF

echo -e "${GREEN}✅ PMO structure created successfully!${NC}"
echo
echo "Board type: $BOARD_TYPE"
if [[ "$BOARD_TYPE" == "5-tool-founder" ]]; then
    echo "- 📥 Triage for raw ideas"
    echo "- 5 queues: Build, Grow, Support, BizOps, Strategy"
    echo "- Perfect for balancing all aspects of your business"
else
    echo "- Standard kanban flow"
    echo "- Backlog → Ready → In Progress → Review → Done"
fi
echo
echo "Next steps:"
echo "1. Review pmo/config.yml and adjust settings"
echo "2. Open pmo/kanban.md in Obsidian to see your board"
echo "3. Create your first spec in pmo/specs/backlog/"
echo "4. Use 'pmo claim <ticket>' to start working"
echo
echo -e "${YELLOW}Note: This PMO is configured for single-repo mode.${NC}"
echo "To enable multi-repo tracking, edit pmo/config.yml"